plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

skills:
  - category: Languages
    skills: [Python, JavaScript, HTML/CSS, C++, SASS]
  - category: Tools/Software
    skills: [Vite, Docker, Git, GitHub, VS Code, CLion, Arduino IDE, PyCharm]
  - category: Frameworks/Libraries
    skills: [React, Flask, Pillow, Nextcord, PyMongo, Discord.py, Discord.js]
  - category: Database/Cloud Hosting
    skills: [PostgreSQL, MongoDB, GitHub Pages, Heroku, DigitalOcean, AWS]
  - category: Other
    skills: [Web Performance, End-to-End Testing, Accessibility, SEO]

projects:
  - name: Fora Bot
    description: Discover one of the most unusual economies found in a Discord Bot.
    github_url: https://github.com/dolsity/fora
    # web_url:
    image_url: "./assets/img/forabot.png"

  - name: Link in Bio
    description: A simple link in bio website only using HTML5/CSS3.
    github_url: https://github.com/Dolsity/link-in-bio
    web_url: https://dolsity.com/link-in-bio
    image_url: "./assets/img/link-in-bio.png"


github_projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 10
  exclude:
    archived: false
    forks: true
    github_projects:
    # - repo-name

social_media:
  instagram: dolsity
  # spotify: 
  # tiktok: dolsity
  github: dolsity
  # youtube: dolsity
  # reddit: dolsity
  # twitch: dolsity
  # discord: 795969792778698763
  stackoverflow: 20505722
  # twitter: dolsity
  # website: http://dolsity.com


link_tree:
  - catagory: Other Socials
    links:
      - name: Instagram
        url: https://instagram.com/dolsity
      - name: GitHub
        url:

  - catagory: Programming
    links:
      - name: Stack Overflow
        url: https://stackoverflow.com/users/20505722/dolsity
      - name: GitHub
        url:

  - name: About Me
    url: "/about"
    icon: user
  - name: Instagram
    url: https://instagram.com/dolsity
    icon: instagram
  - name: GitHub
    url:
    icon: github
  - name: Stack Overflow
    url: https://stackoverflow.com/users/20505722/dolsity
    icon: stack-overflow
  - name: reddit
    url: https://reddit.com/u/dolsity
    icon: Reddit
  - name: Discord
    url: https://discord.com/users/795969792778698763
    icon: discord
  - name: twitch
    url: https://twitch.tv/dolsity
    icon: Twitch
